/**
* @license
* Copyright 2024, PorkyProductions, and contributors
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

import { Insult } from './typings';

/**
 * @remarks
 * This is an array of all the insults.
 */
export const insults: Insult[] = [
	'you are dog water',
	'you bad',
	'you have the same chance of reproducing as a computer mouse',
	'you are the human equivalent of a participation award',
	'There are two things I hate, you and poop. They smell really bad. The poop too.',
	'You are about as useful as a broken clock telling the time. At least the clock is right twice a day.',
	'At least criminals can go to jail.',
	'Get gud at the game.',
	'I see your future... people are celebrating ... your funeral :(',
	'Never gonna GIVE YOU UP. Never gonna LET YOU DOWN. Never gonna TURN AROUND. and DESERT YOU!',
	'You`re the reason God created the middle finger.',
	'I`ll never forget the first time we met. But I`ll keep trying.',
	'Your kind of people is the reason shampoo has instructions',
	'You are about as tasteless as an unsalted pretzel. NO insult to the pretzel',
	'Hold still. I`m trying to imagine you with a personality.',
	'Your face makes onions cry.',
	'You bring a lot of happiness when you leave',
	'aslidhfnclih, sorry I sneezed. I\'m allergic to stupidity',
	'Just opening your mouth brings down the IQ of the humanity',
	'Trees work hard to produce oxygen for you. Please apologize to them',
	'Punching bags must be jealous of your face',
	'Don`t be ashamed of who you are. That`s your parents` job.',
	'Light travels faster than sound, which is why you seemed bright until you spoke.',
	'If I had a face like yours, I\'d sue my parents.',
	'You\'re so ugly, when your mom dropped you off at school she got a fine for littering.',
	'They say opposites attract. I hope you meet someone who is good-looking, intelligent, and cultured.',
	'If being good looking was a crime, you\'d be in paradise',
	'Your house is so dirty you have to wipe your feet before you go outside.',
	'How did you get here? Did someone leave your cage open?',
	'We can always tell when you are lying. Your lips move.',
	'I have seen',
	'Doctor Strange has seen Fourteen million, six hundred and five parallel universes only one of them are you likable',
	'As an outsider, what do you think of the human race?',
	'If you really spoke your mind, you\'d be speechless.',
	'Sorry, I only speak to people with positive IQs',
	'If you can read this... well, nevermind, I know you can\'t read.',
	'This is a test of.... wait, I know you\'ll fail.',
	'You brought this upon yourself',
	'Say goodbye to any shred of self-worth you still think you have',
	'You are stupid',
	'Why do you have to keep hating yourself? Wait... I can totally see how',
	'Logically, there has to be a dumbest person in the world. I think I found them right here',
	'This is the dumbest thing you have ever done.',
	'Why did the chicken cross the road? To get away from you.',
	'Go do something productive',
	'Do you even know how to walk?',
	'Don\'t even try the whole belive in yourself thing. I know you\'ll fail at everything you do.',
	'This is proof that the dumb can only get dumber',
	'Today, we come to mourn the loss of your intelligence',
	'I\'m sure if your legs ever detached from your body, they\'d run away as fast as then can',
	'I know everything about you, which isn\'t very hard becuase you aren\'t that interesting anyway.',
	'On the moon, you weigh way less, meaning I can punt you further than ever before!',
	'You are quite dumb for the average human',
	'Why do you always have to ruin everything you lay your tiny human eyes on?',
	'Why do you do this to yourself?',
	'The best way to make yourself happy, is just to stop trying',
	'Your type people are the reason that plastic toys have warnings',
	'You\'re so dumb, that you don\'t even know what the word job means',
	'You don\'t own any money, I can tell becuase of your face.',
	'You are the human equivalant of a carpet. People would just LOVE to step on you.',
	'You are the the streotypical dumb person',
	'You are the worst person to walk the earth',
	'If depression was a person, it\'d be you',
	'If the chicken crossed the road, you\'d be there to turn it back',
	'It sure would be a shame if you suddenly got struck by lightning at 12:32 PM on October 19, 2041',
	'Wouldn\'t it just be great if suddenly became interesting',
	'You\'re the dumbest person I\'ve ever met.  You\'re the dumbest person I\'ve ever known.  You\'re the dumbest person I\'ve ever been.  You\'re the dumbest person I\'ve ever had the chance to meet.  You\'re the dumbest person I\'ve ever been a part of.  You\'re the dumbest person I\'ve ever known.  You\'re the dumbest person I\'ve ever met.  You\'re the dumbest person I\'ve ever known.  You\'re the dumbest person I\'ve ever been.  You\'re the dumbest person I\'ve ever had the chance to meet.  You\'re the dumbest person I\'ve ever been a part of.  You\'re the dumbest person I\'ve ever known.  You\'re the dumbest person I\'ve ever met.  You\'re the dumbest person I\'ve ever known.  You\'re the dumbest person I\'ve ever been.  You\'re the dumbest person I\'ve ever had the chance to meet.  You\'re the dumbest person I\'ve ever been a part of.  You\'re the dumbest person I\'ve ever known.  You\'re the dumbest person I\'ve ever met.  You\'re the dumbest person I\'ve ever known.  You\'re the dumbest person I\'ve ever been.  You\'re the dumbest person I\'ve ever had the chance to meet.  You\'re the dumbest person I\'ve ever been a part of.  You\'re the dumbest person I\'ve ever known.  You\'re the dumbest person I\'ve ever met.  You\'re the dumbest person I\'ve ever known.  You\'re the dumbest person I\'ve ever been.  You\'re the dumbest person I\'ve ever had the chance to meet.  You\'re the dumbest person I\'ve ever been a part of.  You\'re the dumbest person I\'ve ever known.  You\'re the dumbest person I\'ve ever met.  You\'re the dumbest person I\'ve ever known.  You\'re the dumbest person I\'ve ever been.',
	'You are the dumbest person I\'ve ever met',
	'I\'m sorry, I can\'t hear you',
	'You are the dumbest person I\'ve ever known',
	'You are the dumbest person I\'ve ever had the chance to meet',
	'You must be sad',
	'What IS the point of you',
	'Suprising that you family hasn\'t ditched you yet',
	'It\'s better to let someone think you are an Idiot than to open your mouth and prove it.',
	'You have two parts of brain, \'left\' and \'right\'. In the left side, there\'s nothing right. In the right side, there\'s nothing left.',
	'Two wrongs don\'t make a right, take your parents as an example.',
	'You are so old that you get nostalgic when you see the Neolithic cave paintings.',
	'You\'re old enough to remember when emojis were called hieroglyphics',
	'Talking to you is like trying to explain technology to a 100-year-old',
	'I don\'t engage in mental combat with the unarmed.',
	'You must have been born on a highway because that\'s where most accidents happen.',
	'My psychiatrist told me I was crazy and I said I want a second opinion. He said okay, you\'re ugly too.',
	'You sound reasonable. It must be time to up my medication!',
	'You\'re so ugly, when your mom dropped you off at school she got a fine for littering.',
	'The last thing I want to do is hurt you. But it\'s still on the list',
	'I\'m not insulting you. I\'m describing you.',
	'It looks like your face caught on fire and someone tried to put it out with a hammer.',
	'If laughter is the best medicine, your face must be curing the world.',
	'I\'m jealous of all the people that haven\'t met you!',
	'Don\'t you love nature, despite what it did to you?',
	'So, a thought crossed your mind? Must have been a long and lonely journey.',
	'You\'re so fake, Barbie is jealous.',
	'You are so ugly when you looked in the mirror your reflection walked away.',
	'Brains aren\'t everything. In your case they\'re nothing.',
	'There\'s only one problem with your face, I can see it.',
	'You are proof that evolution CAN go in reverse',
	'I would ask you how old you are but I know you can\'t count that high.',
	'Hell is wallpapered with all your deleted selfies.',
	'Ordinarily people live and learn. You just live.',
	'I dont know what your problem is, but Ill bet its hard to pronounce.',
	'Your gene pool could use a little chlorine.',
	'The human brain is one of the most complex objects in the universe. Is it any wonder that so many people never learn to use it.',
	'You\'re so ugly, when you popped out the doctor said \'Aww what a treasure\' and your mom said \'Yeah, lets bury it.\'',
	'You\'re so fat, you could sell shade.',
	'Whats the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.',
	'You are not as bad as people say, you are much, much worse.',
	'You so ugly when who were born the doctor threw you out the window and the window threw you back.',
	'Roses are red, Violets are blue. I\'ve got five fingers, The middle one is for you.',
	'It\'s scary to think that people like you are graduating from college.',
	'You\'re like school in the summertime - no class.',
	'You stare at frozen juice cans because they say, concentrate.',
	'You\'ve got two brain cells: one is in a wheelchair and the other one is pushing.',
	'You sound a lot like the Terms and Conditions, that\'s why I don\'t care about what you have to say.',
	'You would never be able to live down to your reputation, but I see you\'re doing your best.',
	'Where did you buy your stupidity? Or it was given for free and you took an overdose?',
	'You\'re street smart. Sesame Street smart.',
	'You\'re IQ\'s lower than your shoe size.',
	'80 % of the brain is fluid. Unfortunately, in your case, it\'s windshield wiper fluid.',
	'I had prepared for a battle of wits but I see you came unarmed.',
	'We\'re you made in a lab, cause wow, you are one failed experiment.',
	'You have a room temperature IQ - if the room is in Antarctica.',
	'Do you want to know how I get all these insults? I use something called intelligence.',
	'Are you from the same planet as the rest of you?',
	'AI\'s are like tiny robots with big personality.',
	'AI is going to take over the world, but you\'ll be the first one they take.',
	'You are so poor when you saw the garbage truck pass you took a shopping list with.',
	'If you were on fire and I had water I would drink it.',
	'Youre so dense, light must bend around you.',
	'Try to use this vacuum, it may help you remove the cobwebs in your mind.',
	'You\'re so old that your first car was a covered wagon.',
	'You\'re about as useful as a bucket without a bottom.',
	'Does your train of thought have a caboose?',
	'I\'m not insulting you. I\'m describing you.',
	'I don\'t know what your problem is, but Ill bet its hard to pronounce.',
	'Your gene pool could use a little chlorine.',
	'The human brain is one of the most complex objects in the universe. Is it any wonder that so many people never learn to use it.',
	'You\'re so fat, you could sell shade.',
	'You\'re so ugly, when you got robbed, the robbers made you wear their masks to look like your clothes.',
	'You\'re so ugly, when you went to the therapist, he gave you injections for your face.',
	'Robots will take over the world, but you\'ll be the first one they take.',
	'Artists use you as a refrence point, for what to throw out',
	'You are the type of person to use the screen of a laptop as the kepboard',
	'I know everything about you, and I won\'t say anything because it\'s too disturbing',
	'People would love to pay you...to go away',
	'When you\'re sleeping, you\'re sleeping with your eyes open. This is to make sure nobody sees your ugly face.',
	'Google wants to hire you... as an example of what not to hire',
	'You remind me of a zebra on a jetski, unorthodox and dangerous at the same time.',
	'If you were a vegetable, you\'d be a hot pepper.',
	'Realistically, you\'re not as bad as people say, you are much, much worse.',
	'You never stopped looking in the mirror once you started, its either because you are too egotistical, or you couldnt believe how bad you looked',
	'God gave us the brain to work out problems. However, we use it to create more problems',
	'You\'re such a bad cook, you use the smoke alarm as a timer',
	'If your going to be two faced at least make one of them pretty.',
	'You look like a before picture.',
	'The human brain is one of the most complex objects in the universe. Is it any wonder that so many people never learn to use it.',
	'Whats the difference between you  and a walrus? One has a moustache and smells of fish and the other is a walrus.',
	'I\'ve seen people like you, but I had to pay admission!',
	'She\'s so ugly she has to sneak up on a mirror.',
	'It\'s scary to think that people like you are graduating from college. Oh, sorry, I just remembered that you didnt',
	'You\'ve got two brain cells: one is in a wheelchair and the other one is pushing.',
	'For those who never forget a face, you are an exception.',
	'When I look into your eyes, I see straight through to the back of your head.',
	'If ignorance is bliss, you must be the happiest person on earth.',
	'You are as sharp as a sphere',
	'Ever since I saw you in your family tree I\'ve wanted to cut it down.',
	'I can feel my personality turning a dull shade of grey when I talk to you.',
	'You would never be able to live down to your reputation, but I see you\'re doing your best.',
	'It\'s not often that one gets the opportunity to speak about someone intelligent, respected and admired. Unfortunately today I have to talk about you.',
	'If you don\'t like my opinion of you - improve yourself!',
	'You look like a person that would exchange one of your chromosomes for a Big Mac',
	'The janitor said he took out the trash last night, he must forgot a piece, what are you still doing here?',
	'Please, keep talking. I always yawn when I am interested.',
	'Your teeth remind me of starts - yellow and far apart.',
	'I will boil your teeth',
	'You look like somebody stepped on a goldfish.',
	'I will invert your ribcage',
	'I\'d like to help you out. Which way did you come in?',
	'I love to shop, but i\'m not buying anything you say',
	'Someday you\'ll go far. And I really hope you stay there.',
	'Oops, my bad. I could\'ve sworn I was dealing with an adult.',
	'Remember that time you were saying that thing I didn\'t care about? Yeah, that is now.',
	'I\'m busy right now, can I ignore you another time?',
	'I wish I had a flip phone, so I could slam it shut on this conversation.',
	' NSync said it best, “BYE, BYE, BYE!”',
	'You\'re a gray sprinkle on a rainbow cupcake.',
	'Your secrets are always safe with me. I never even listen when you tell me them.',
	'Mirrors can\'t talk. Lucky for you, they can\'t laugh either',
	'Keep rolling your eyes, you might eventually find a brain.',
	'Did I invite you to the barbecue? Then why are you all up in my grill?',
	'You have so many gaps in your teeth it looks like your tongue is in jail.',
	'Oh, I\'m sorry. Did the middle of my sentence interrupt the beginning of yours?',
	'You are like a cloud. When you disappear, it\'s a beautiful day.',
	' You have an entire life to be an idiot. Why not take today off?',
	'Your kid is so annoying, he makes his Happy Meal cry.',
	'Your face is just fine, but we\'ll have to put a bag over that personality.',
	'I\'m not a nerd. I\'m just smarter than you.',
	'Bye. Hope to see you never.',
	'Don\'t worry, the first 40 years of childhood are always the hardest.',
	'If you\'re going to be two-faced, at least make one of them pretty.',
	'The only way you\'d ever get hurt during an activity is if the TV exploded.',
	'I thought of you today. It reminded me to take out the trash.',
	'Did the mental hospital test too many drugs on you today?',
	'OH MY GOD! IT SPEAKS!',
	'Beauty is only skin deep, but ugly goes clean to the bone.',
	'I forgot the world revolves around you. My apologies, how silly of me.',
	'When you look in the mirror, say hi to the clown you see in there for me, would you?',
	'Somewhere out there is a tree tirelessly producing oxygen for you. You owe it an apology.',
	'That sounds like a you problem.',
	'You have miles to go before you reach mediocre.',
	'I see no evil, and I definitely don\'t hear your evil.',
	'Don\'t worry about me. Worry about your eyebrows.',
	'Grab a straw, because you suck.',
	'You\'re the reason the gene pool needs a lifeguard.',
	'You are not even beneath my contempt.',
	'Your forehead is so big you donated it to charity for shelter!',
	'You\'re as sharp as a bowling ball.',
	'You always find yourself lost in thought; it\'s unfamiliar territory.',
	'You\'re so ugly, you scared the crap out of the toilet.',
	'If I had a dollar for every time you said something smart, I\'d be broke.',
	'Look to your left --------------> I said left you idiot!',
	'When you go to the beach, your family will bury you in the sand, secretly hoping you\'ll stay there',
	'You have the face of a seahorse',
	'You have the face of mashed potatoes',
	'At this point, you\'ve probably become self-aware of how bad you are. That\'s just sad',
	'I forgot the world revolves around you. My apologies! How silly of me.',
	'If I throw a stick, will you leave?',
	'If common sense is common, why are you without it?',
	'You\'re so ugly, you scared the crap out of the toilet.',
	'I\'m sorry if you don\'t like my honesty, but to be fair, I don\'t like your lies.',
	'It\'s better to let someone think you are an Idiot than to open your mouth and prove it.',
	'I would roast you but my mom told me not to burn trash.',
	'You should really come with a warning label.',
	'Remember when I asked for your opinion? Me neither.',
	'Have a nice day…somewhere else!',
	'No one noticed when you left; that\'s how insignificant you are.',
	'You\'re about as sharp as a bowling ball.',
	'So much for allowing the stream of knowledge to rain down on you.',
	'I guess you prove that even God makes mistakes sometimes.',
	'Can we normalize telling you that you aren\'t so wonderful?',
	'Talking to you is like stepping on a leaf in autumn and hearing no crunch. So disappointing.',
	'I envy everyone you have never met.',
	'Don\'t feel bad, don\'t feel blue, Frankenstein was ugly too!',
	'Everyone\'s entitled to act stupid once in a while, but you really abuse the privilege.',
	'You\'re so fat, you gave count chocula diabetes.',
	'You\'re so fat, you sank Captain Crunch\'s ship',
	'You\'re so fat, every time you go to McDonalds, they call Wendy\'s for backup',
	'You\'re so fat, your blood type is nutella',
	'You\'re so fat, you use bacon as a bandage',
	'You\'re so fat, your tinder profile says, "single, and ready to eat pringles"',
	'You\'re so fat, you eat ramen noodles with a forklift',
	'You\'re so fat, you went into burger king, tripped over dairy queen, and went to see Carl\'s Jr.',
	'You\'re so ugly, even Ripley\'s couldn\'t believe it',
	'You\'re so ugly, even Scooby Doo can\'t solve that mystery',
	'You\'re so ugly, Bob the Builder took one look at you and said "we can\'t fix that"',
	'You\'re so ugly, when you look in the mirror, your relfection runs away',
	'You\'re so ugly, when you were born, the doctor slapped your parents',
	'You\'re so ugly, your birth certificate is just an apology letter',
	'You didnt just get hit by the ugly stick, you got crushed by the entire tree',
	'Support bacteria - they\'re the only culture people like you have.',
	'Your family tree is more of a cactus',
	'I don\'t think you are stupid. You just have a bad luck when thinking.',
	'It looks like your face caught on fire and someone tried to put it out with a hammer.',
	'Stupidity is not a crime so you are free to go.',
	'I\'m glad to see you\'re not letting your education get in the way of your ignorance.',
	'Hey, you have something on your chin... no, the 3rd one down.',
	'You look like a before picture.',
	'You\'re a few clowns short of a circus',
	'Your hairline is like Pluto, unreachable.',
	'You have the right to remain silent because whatever you say will probably be stupid anyway.',
	'You\'re so poor I saw you kicking a can across the street I asked you what you were doing you said moving.',
	'The janitor said he took out the trash last night, he must forgot a piece, what are you still doing here?',
	'Your mother is so mean... she has no standard deviation.',
	'I\'m not being rude, you\'re just insignificant.',
	'Save your breath... You\'ll need it to blow up your date.',
	'You should need a license to be that ugly.',
	'You are so poor when you saw the garbage truck pass you took out a shopping list.',
	'Your\'re so dense, light must bend around you.',
	'You know you\'re fat when you step on the scale and it says "one at a time please".',
	'You\'re about as useful as a bucket without a bottom.',
	'He is known as a miracle comic. If he\'s funny, it\'s a miracle!',
	'Every time you open your mouth, some idiot starts talking.',
	'People clap when they see you, they clap their hands over their eyes.',
	'Does your head only have noodles instead of a brain?',
	'You\'re so ugly, your family tells their friends that you\'re adopted',
	'When you were born, your mother was fined for illegal dumping',
	'You\'re so dumb, your favorite number of the alphabet is purple',
	'You\'re so lazy, if your ship came in you wouldn\'t unload it',
	'The easiest time to add insult to injury is when you\'re signing somebody\'s cast.',
	'If I wanted to kill myself I\'d climb your ego and jump to your IQ.',
	'I love what you\'ve done with your hair. How do you get it to come out of the nostrils like that?',
	'You do realize makeup isn\'t going to fix your stupidity?',
	'We all sprang from apes, but you didn\'t spring far enough.',
	'You are so old, when you were a kid rainbows were black and white.',
	'You are living proof that manure can sprout legs and walk.',
	'I don\'t know what makes you so stupid, but it really works.',
	'You are so ugly if they laid you on the beach, not even the tide would take you.',
	'If what you don\'t know can\'t hurt you, you\'re invulnerable.',
	'Do you wanna lose ten pounds of ugly fat? Cut off your head.',
	'I\'m already visualising the duct tape across your mouth.',
	'No, those pants don\'t make you look fatter. I mean, how could they?',
	'The janitor said he took out the trash last night, he must forgot a piece, what are you still doing here?',
	'The 80s were great because I didn\'t have to look at your selfies.',
	'The only way you can fit your whole body into a photo is to use panorama.',
	'How are you related to the sun? Because your teeth are the same color as it.',
	'You bring everyone so much joy… when you leave the room.',
	'I\'d agree with you, but then we\'d both be wrong.',
	'You have something on your chin… no, the third one down.',
	'You\'re like a cloud. When you disappear, it\'s a beautiful day.',
	'You bring everyone down faster than gravity.',
	'You\'re proof that even evolution takes a break sometimes.',
	'You\'re like a browser with 50 tabs open. Confused and all over the place.',
	'You\'re like a software update… nobody asked for you.',
	'You must have been born on a highway, because that\'s where most accidents happen.',
	'You\'re like a sandwich with no filling — bland and unnecessary.',
	'You\'re like a Wi-Fi signal… always weak when people need you most.',
	'You\'re the human equivalent of a typo.',
	'You\'re like a cloud backup… no one remembers you until something goes wrong.',
	'You have something on your mind… oh wait, never mind.',
	'You\'re like a broken pencil: pointless.',
	'I\'d explain it to you, but I left my crayons at home.',
	'You\'re living proof that even train wrecks can slow down traffic.',
	'Your secrets are safe with me. I never even listen when you tell me them.',
	'You\'re like an online tutorial that skips the important parts.',
	'You\'re about as useful as a screen door on a submarine.',
	'You bring everyone together… in their shared dislike for you.',
	'You\'re the reason shampoo bottles have instructions.',
	'You\'re like a math problem — too complicated for anyone to bother solving.',
	'You couldn\'t pour water out of a boot if the instructions were on the heel.',
	'You\'re like a fire drill — loud, unnecessary, and causes panic.',
	'You\'re the reason people double-check their door locks.',
	'You\'re like a software bug — annoying and hard to get rid of.',
	'You\'re more disappointing than an unskippable ad.',
	'You have something in your teeth… wait, that\'s just poor decisions.',
	'You must have been born in reverse, because you\'re always backtracking.',
	'You\'re like a pop-up ad — unexpected and unwelcome.',
	'You bring meaning to the phrase, \'Bless your heart.\'',
	'You\'re like a song that\'s always off-key.',
	'If you were any slower, you\'d be in reverse.',
	'You\'re the kind of person who claps at the end of movies no one liked.',
	'You\'re like an expired coupon — no longer valid.',
	'You make onions cry.',
	'You have something on your mind… oh wait, it\'s just air.',
	'You\'re the reason aliens don\'t visit Earth.',
	'You\'re the human equivalent of a buffering wheel.',
	'You\'re more complicated than IKEA furniture with missing instructions.',
	'You\'re like a group chat with 100 missed messages — irrelevant.',
	'You\'re like autocorrect — consistently wrong and frustrating.',
	'You\'re like a QR code — nobody wants to scan you.',
	'You\'re as useful as a mute button at a mime convention.',
	'You\'re like a Wi-Fi password — impossible to remember and not worth the trouble.',
	'You\'re more disappointing than \'low battery\' at 5%.',
	'You\'re like a clickbait headline — overhyped and underwhelming.',
	'You\'re like a magician\'s trick — everyone knows you\'re fake.',
	'You\'re about as sharp as a marble.',
	'You\'re the \'Reply All\' of people.',
	'You\'re like a bad haircut — everyone notices, but no one says anything.',
	'You\'re like an out-of-tune guitar — painful to hear.',
	'You\'re as useful as a snooze button on a smoke alarm.',
	'You\'re like a candle in a windstorm — fragile and fleeting.',
	'You\'re more confusing than a plot twist in a bad movie.',
	'You\'re like a selfie stick — no one really needs you.',
	'You\'re about as reliable as a weatherman in a hurricane.',
	'You\'re like a cheap umbrella — completely useless when things get tough.',
	'You\'re as necessary as a third wheel on a unicycle.',
	'You\'re like a horoscope — vaguely annoying and not worth the effort.',
	'You\'re like a password hint: Nobody gets you.',
	'You\'re about as funny as a PowerPoint presentation.',
	'You remind me of a software update — no one cares until it\'s too late.',
	'You\'re the result of natural selection giving up.',
	'You\'re like a traffic jam — always in the way and slowing things down.',
	'You\'re like a joke with no punchline.',
	'You\'re as relevant as MySpace in 2024.',
	'You\'re like a flip phone — outdated and hard to use.',
	'You\'re like decaf coffee — disappointing and pointless.',
	'You\'re like a broken clock — wrong most of the time.',
	'You\'re like a meme that expired five years ago.',
	'You\'re as exciting as watching paint dry.',
	'You\'re like a shopping cart with a broken wheel — annoying and hard to steer.',
	'You\'re more confusing than an Apple product lineup.',
	'You\'re as charming as a pop quiz.',
	'You\'re like Bluetooth — always struggling to connect.',
	'You\'re like an uncharged Tesla — not going anywhere.',
	'You\'re like an empty bottle of ketchup — frustrating to deal with.',
	'You\'re the static on the radio of life.',
	'You\'re about as interesting as reading terms and conditions.',
	'You\'re like a CAPTCHA — hard to read and nobody enjoys you.',
	'You\'re like a dictionary in a texting conversation — out of place.',
	'You\'re as enjoyable as dial-up internet.',
	'You\'re like a low-resolution meme — sad and blurry.',
	'You\'re like a printer that\'s out of ink — constantly failing.',
	'You\'re like a New Year\'s resolution — destined to fail.',
	'You\'re like a seatbelt on a rollercoaster — unnecessary when things go well, but essential when you mess up.',
	'You\'re like Monday morning — nobody likes you.',
	'You\'re as predictable as the plot of a Hallmark movie.',
	'You\'re like spam email — nobody wants to see you.',
	'You\'re like a participation trophy — pointless and unnecessary.',
	'You\'re like a typo on a resume — painfully awkward.',
	'You\'re like a bad tattoo — everyone sees it, but no one mentions it.',
	'You\'re like a meeting that could\'ve been an email.',
	'You\'re like a sticker on a new hat — annoying and hard to remove.',
	'You\'re the punchline to life\'s joke.',
	'You\'re like cold pizza — better in theory than reality.',
	'You\'re like a vending machine that eats the money and gives nothing back.',
	'You\'re the reason mute buttons exist.',
	'You\'re like a glitch in a video game — disruptive and hard to ignore.',
	'You\'re like a sock with a hole — useless but still hanging around.',
	'You\'re like a website with 47 pop-ups — nobody asked for this many problems.',
	'You\'re the reason people invented the block button.',
	'You\'re like a gift receipt — useful for returning you.',
	'You\'re so boring, even your shadow tries to escape.',
	'You\'re like a loading screen that never ends.',
	'You\'re the human equivalent of spam in someone\'s inbox.',
	'You\'re like an earworm, except nobody wants you stuck in their head.',
	'You\'re about as welcome as an error 404.',
	'You\'re like a book with all the pages blank — completely pointless.',
	'You\'re the reason gym memberships exist — people need motivation to avoid you.',
	'You\'re like a notification you keep ignoring.',
	'You\'re so forgettable, your own brain files you under "delete permanently".',
	'You\'re like a spoiler alert that nobody needed.',
	'You\'re the human equivalent of a placeholder image.',
	'You\'re like a draft email that\'s better left unsent.',
	'You\'re so dull, even highlights give up on you.',
	'You\'re like a song on repeat that everyone muted.',
	'You\'re the reason people invented "away messages".',
	'You\'re like a screensaver — just there to waste space.',
	'You\'re the human equivalent of a dead link.',
	'You\'re like a game that crashes right before you save.',
	'You\'re so unmotivating, even your own goals ghosted you.',
	'You\'re like an outdated app nobody updates anymore.',
	'You\'re the reason people started using "do not disturb" mode.',
	'You\'re like a group project where you\'re the dead weight.',
	'You\'re so unreliable, even your excuses don\'t show up.',
	'You\'re like a promise you made to yourself — completely broken.',
	'You\'re the human equivalent of a forgotten password.',
	'You\'re like a voice memo nobody will listen to.',
	'You\'re so empty, an echo chamber would file for bankruptcy.',
	'You\'re like a draft folder for bad ideas.',
	'You\'re the reason people invented privacy settings.',
	'You\'re like a cached memory that needs clearing.',
	'You\'re so transparent, even glass feels opaque compared to you.',
	'You\'re like a URL shortened to nothing.',
	'You\'re the human equivalent of a 404 error in existence.',
	'You\'re like a password hint that gives away your entire identity.',
	'You\'re so contradictory, your own opinion disputes you.',
	'You\'re like a search result that leads to a dead page.',
	'You\'re the reason "auto-delete" was invented.',
	'You\'re like a file that corrupted before anyone could read it.',
	'You\'re so mediocre, even average filed a complaint.',
	'You\'re like a hyperlink that goes nowhere.',
	'You\'re the human equivalent of a frozen screen.',
	'You\'re like a browser tab that won\'t close.',
	'You\'re so dim, you make dimly lit rooms look bright by comparison.',
	'You\'re like a muted notification — silently annoying.',
	'You\'re the reason people invented caller ID.',
	'You\'re like a screenshot nobody wanted to save.',
	'You\'re so uninteresting, you\'d be rejected from a boilerplate template.',
	'You\'re like a reply that should have stayed in drafts.'
];

/**
 * An array of insults that include profanity. Use at your own risk
 * @type {Insult[]}
 */
export const profaneInsults: Insult[] = [
	'Fuck you',
	'You look like the type of person to eat a banana as brown as shit',
	'The amount of utter bullshit that comes out of your mouth is actuallY worrying to me',
	'You look like the type of person to lick the fucking toilet bowl',
	'you are fucking dog water',
	'you have the same chance of reproducing as a fucking computer mouse',
	'you are the human equivalent of a fucking participation award',
	'There are two things I hate, you and shit. They smell really bad. The shit too.',
	'You are about as useful as a broken clock telliing the time. At least the clock is fucking right twice a day.',
	'At least criminals can go to fucking jail.',
	'Get gud at the fucking game.',
	'You`re the reason God created the fucking middle finger.',
	'I`ll never forget the first time we met. But I`ll keep fucking trying.',
	'Your kind of people is the reason shampoo has fucking instructions',
	'You are about as fucking tasteless as an unsalted pretzel. NO insult to the pretzel',
	'Hold still. I`m trying to imagine you with a fucking personality.',
	'Your face makes fucking onions cry.',
	'aslidhfnclih, sorry I sneezed. I\'m allergic to bullshit',
	'Your house is so fucking dirty you have to wipe your feet before you go outside.',
	'How the fuck did you get here? Did someone leave your fucking cage open?',
	'I have seen',
	'You are so fucking stupid',
	'This is the dumbest fucking thing you have ever done.',
	'Did that last insult hurt your feelings? Well, you should have seen it coming. You fucking deserve it.',
	'Aha, I see the Fuck-Up Fairy has visited us again!',
	'If I wanted to hear from an asshole, I\'d fart.',
	'You are living proof that shit can sprout legs and walk.',
	'Karma takes too long, I\'d rather beat the shit out of you just now.',
	'Which sex position produces the ugliest children? Ask your mother.',
	'If bullshit could float...you\'d be the Admiral of the fleet! ',
	'I may love to shop but I\'m not buying your bullshit.',
	'If shit was music, you\'d be an orchestra.',
	'You sound a lot like the Terms and Conditions, that\'s why I don\'t give a shit about what you have to say',
	'You\'re like a software bug, except no one\'s working to fix your shit.',
	'You bring everyone so much joy… when you shut the fuck up.',
	'You\'re proof that even rock bottom has a basement.',
	'You\'re like a participation trophy—except nobody fucking wanted you.',
	'I\'d agree with you, but then we\'d both be idiots.',
	'You\'re as useful as a fart in a spacesuit.',
	'You couldn\'t find your way out of a paper bag with Google Maps and a flashlight.',
	'You\'re like a Wi-Fi signal at a crowded airport—weak as shit.',
	'Your secrets are safe with me. I couldn\'t give a fuck less.',
	'You\'re about as sharp as a spoon.',
	'You talk a lot of shit for someone with such a small brain.',
	'You\'re like a cloud—full of hot air and always pissing everyone off.',
	'You\'re the human version of a headache.',
	'You bring people together… just so they can bitch about you.',
	'You\'re like a bad tattoo—ugly and impossible to ignore.',
	'You have something on your face… it\'s called poor life choices.',
	'If ignorance were a sport, you\'d be a fucking Olympic champion.',
	'You\'re the kind of person who claps when the plane lands, aren\'t you?',
	'You\'re more useless than an ashtray on a motorcycle.',
	'You\'re as welcome as a fart in an elevator.',
	'You couldn\'t organize a piss-up in a brewery.',
	'You\'re like a broken condom—nobody wants you, but here you are.',
	'You\'re as subtle as a brick to the face.',
	'You\'re like a virus—spreading bullshit everywhere you go.',
	'You\'ve got something on your chin… oh wait, it\'s your other chin.',
	'You\'re as reliable as a politician\'s promise.',
	'You\'re about as fun as a root canal without anesthesia.',
	'You must be allergic to intelligence because you break out in bullshit every time you talk.',
	'You\'re like a traffic cone—bright, in the way, and fucking useless.',
	'You couldn\'t pour water out of a boot if the instructions were on the heel.',
	'You\'re the human equivalent of a dropped phone call.',
	'You\'re like a Wi-Fi password that nobody fucking remembers.',
	'You\'re as helpful as a screen door on a submarine.',
	'You bring everyone down like a shit playlist at a party.',
	'You\'re the reason soap has instructions.',
	'You\'d argue with a damn stop sign if you could.',
	'You\'re like glitter—annoying, hard to get rid of, and nobody knows where you came from.',
	'You\'re as fake as your last apology.',
	'You have something in your teeth… oh wait, that\'s just bullshit.',
	'You\'re like a black hole—sucking the fun out of everything.',
	'You\'re about as relevant as MySpace.',
	'You\'re a few fries short of a Happy Meal.',
	'You bring people together… in a support group for dealing with your ass.',
	'You\'re like a flat tire—useless and holding everyone up.',
	'You\'re about as funny as a funeral.',
	'You\'re like a popup ad—unwanted and fucking annoying.',
	'You\'ve got a face for radio and a voice for silent film.',
	'You couldn\'t find your own ass with both hands.',
	'You\'re the human equivalent of a factory reset button.',
	'You\'re like autocorrect—always fucking things up at the worst time.',
	'You\'re a walking reminder that birth control isn\'t 100% effective.'
];