/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,js,svelte,ts}', 'index.html'],
  theme: {
    fontFamily: {
      primary: ['Raleway', 'sans-serif'],
    },
    extend: {
      colors: {
        primaryMajorelleBlue: '#4f46e5',
        'primary-majorelle-blue': '#4f46e5',
        secondaryOrangePantone: '#F75C03',
        'secondary-orange-pantone': '#F75C03',
        tertiaryMauve: '#DABFFF',
        'tertiary-mauve': '#DABFFF',
        themeRed: '#db0000',
        'theme-red': '#db0000',
        themeOrange: '#ff7b00',
        'theme-orange': '#ff7b00',
        themeYellow: '#ffbb00',
        'theme-yellow': '#ffbb00',
        themeLime: '#00ff22',
        'theme-lime': '#00ff22',
        themeGreen: '#046d00',
        'theme-green': '#046d00',
        themeLightBlue: '#00fffb',
        'theme-light-blue': '#00fffb',
        themeBlue: '#001eff',
        'theme-blue': '#001eff',
        themeBlueVibrant: '#0000F4',
        'theme-blue-vibrant': '#0000F4',
        themeIndigo: '#6f00ff',
        'theme-indigo': '#6f00ff',
        themePurple: '#36008c',
        'theme-purple': '#36008c',
        themePink: '#ff00d4',
        'theme-pink': '#ff00d4',
        themeWhite: '#fffff6',
        'theme-white': '#fffff6',
        themeBlack: '#0a0a0a',
        'theme-black': '#0a0a0a',
      },
    },
  },
  plugins: [],
};
