version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00"
      timezone: "America/New_York"

    open-pull-requests-limit: 10

    allow:
      - dependency-type: "direct"

    commit-message:
      prefix: "Upgrade"
      include: "scope"

    labels:
      - "dependencies"
      - "automated"

    groups:
      frontend-framework:
        patterns:
          - "@types/react*"
          - "astro*"
          - "@astrojs/*"
          - "react"
          - "react-dom"
          - "svelte"
          - "vue"
        update-types:
          - "minor"
          - "patch"

    ignore:
      - dependency-name: "demotivator"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jquery"
        update-types: ["version-update:semver-major"]
      - dependency-name: "uadetect"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@porkyproductions/hat"
        update-types: ["version-update:semver-major"]
      - dependency-name: "bootstrap-icons"
        update-types: ["version-update:semver-major"]
      - dependency-name: "lodash"
        update-types: ["version-update:semver-major"]

    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00"
      timezone: "America/New_York"

    open-pull-requests-limit: 10

    allow:
      - dependency-type: "development"

    commit-message:
      prefix: "Upgrade"
      include: "scope"

    labels:
      - "dev-dependencies"
      - "automated"
      - "auto-merge"

    groups: {}

    versioning-strategy: "increase"
