export const tweets: string[] = [
  "I just got harassed a disturbing amount by this website called (de)Motivator. Check it out: https://demotivator.web.app/",
  "I can't get enough of this (de)motivator web app! It's been harassing me with anti-motivational quotes all day. Check it out: https://demotivator.web.app/ #demotivation",
  "I just got hit with a disturbing amount of demotivation from this website called (de)Motivator. You gotta try it out: https://demotivator.web.app/ #demotivation",
  "I was feeling too motivated, but this (de)Motivator web app put a stop to that real quick. Check it out: https://demotivator.web.app/ #demotivation",
  "If you're tired of all the positivity, you need to try out this (de)Motivator web app. It's been demotivating me all day and it's glorious. https://demotivator.web.app/ #demotivation",
  "I don't know why I keep coming back to this (de)Motivator web app, but it's just too good. Check it out: https://demotivator.web.app/ #demotivation",
  "I thought I wanted success, but this (de)Motivator web app showed me the light. Join me in demotivation and check it out: https://demotivator.web.app/ #demotivation",
  "I used to aim for the stars, but now I just aim for the mud thanks to this (de)Motivator web app. Try it out: https://demotivator.web.app/ #demotivation",
  "I was procrastinating all day until this (de)Motivator web app came along and showed me the true path to failure. Check it out: https://demotivator.web.app/ #demotivation",
  "I never knew I needed a web app that would lower my standards until I found (de)Motivator. It's a game changer. Check it out: https://demotivator.web.app/ #demotivation",
  "I can't believe how fast this (de)Motivator web app demotivates me. It's like lightning in a bottle. Check it out: https://demotivator.web.app/ #demotivation",
  "I just tried this (de)Motivator web app and it's like a life coach, but for losers. You gotta check it out: https://demotivator.web.app/ #demotivation",
  "If you're tired of chasing your dreams, try this (de)Motivator web app. It's like a warm blanket of failure. https://demotivator.web.app/ #demotivation",
  "I can't believe how much time I've wasted being productive. This (de)Motivator web app showed me the error of my ways. Check it out: https://demotivator.web.app/ #demotivation",
  "I never knew demotivation could be so addictive until I found this (de)Motivator web app. It's like a drug, but for quitters. https://demotivator.web.app/ #demotivation",
  "I used to think success was the key to happiness. Boy, was I wrong. This (de)Motivator web app showed me the path to true misery. Check it out: https://demotivator.web.app/ #demotivation",
  "I don't know why anyone would want to be motivated when they could just use this (de)Motivator web app and settle for mediocrity. Join me in the dark side: https://demotivator.web.app/ #demotivation",
  "I don't need a life coach anymore. I just use this (de)Motivator web app and let it crush my dreams for me. Check it out: https://demotivator.web.app/ #demotivation",
  "This (de)Motivator web app is like a genie that grants wishes, but instead of wishes it gives you disappointment. Try it out: https://demotivator.web.app/ #demotivation",
  "I never knew how much I needed a web app that would make me feel like a loser until I found (de)Motivator. It's like therapy, but for quitters. https://demotivator.web.app/ #demotivation",
  "If you're tired of all the positivity and success stories, you need this (de)Motivator web app in your life. It's like a slap in the face, but for your dreams. Check it out: https://demotivator.web.app/ #demotivation",
];
